// All 100+ wishes for Rola's Wish Jar
export const wishes: string[] = [
  "May every day of your new year be filled with joy and laughter 💕",
  "Wishing you a year as beautiful as your smile 🌸",
  "May your dreams bloom like flowers in spring 🌷",
  "You deserve all the happiness in the world, Rola ✨",
  "May love find you in the most magical ways 💖",
  "Here's to a year of adventures and unforgettable memories 🌍",
  "May your heart always be light and your spirit always be bright 🌟",
  "Wishing you moments that take your breath away 🦋",
  "May every sunset remind you of how beautiful life is 🌅",
  "You are a ray of sunshine in everyone's life ☀️",
  "May this year bring you everything your heart desires 💝",
  "Wishing you peace, love, and endless happiness 🕊️",
  "May your laughter echo through the mountains 🏔️",
  "You are stronger than you know and braver than you believe 💪",
  "May every morning greet you with a reason to smile 🌻",
  "Wishing you a year full of beautiful surprises 🎁",
  "May you always find beauty in the ordinary moments 🌿",
  "Here's to growing, glowing, and knowing your worth 👑",
  "May your path be lined with love and guided by stars ⭐",
  "Wishing you the courage to chase every dream 🦅",
  "May this birthday mark the beginning of your most magical year yet ✨",
  "You light up every room you walk into 💡",
  "May every door open wide for you this year 🚪",
  "Wishing you a heart full of gratitude and joy 🙏",
  "May you dance through life with grace and confidence 💃",
  "Here's to new chapters and beautiful stories 📖",
  "May your wishes outnumber the stars 🌠",
  "Wishing you health, wealth, and endless love 💰",
  "May every challenge you face make you stronger 🌊",
  "You are worthy of every good thing coming your way 🌈",
  "May this year be your best chapter yet 📚",
  "Wishing you spontaneous adventures and peaceful nights 🌙",
  "May your energy attract all good things 🔮",
  "Here's to being unapologetically you 💋",
  "May you always have the love of those who matter most 👨‍👩‍👧",
  "Wishing you warmth in winter and cool breezes in summer 🍃",
  "May every meal taste delicious and every nap be refreshing 😴",
  "You deserve a love story more beautiful than any fairy tale 🏰",
  "May your creative spirit soar to new heights 🎨",
  "Wishing you clarity, purpose, and direction this year 🧭",
  "May every hug you receive feel like home 🏠",
  "Here's to celebrating you, today and every day 🥂",
  "May your playlist always have the perfect song 🎵",
  "Wishing you a circle of friends who truly uplift you 🤝",
  "May you bloom exactly where you're planted 🌺",
  "May every storm in your life lead to a beautiful rainbow 🌈",
  "Wishing you the wisdom to know your own worth 🦁",
  "May your kindness come back to you a thousandfold 💝",
  "Here's to saying yes to life's best moments 🙌",
  "May you always find your way back to happiness 🧡",
  "Wishing you lazy weekend mornings and exciting weekday adventures ☕",
  "May every photo you take capture a perfect memory 📸",
  "You have the power to create the life you dream of 🌟",
  "May your social media always bring you joy and connection 📱",
  "Wishing you a year of beautiful transformations 🦋",
  "May love be your compass and joy be your destination ❤️",
  "Here's to all the places you haven't explored yet 🗺️",
  "May your confidence grow with every passing day 💫",
  "Wishing you the luxury of time — to rest, to play, to dream 🌙",
  "May every candle you blow make your wish come true 🕯️",
  "You are a masterpiece in progress, Rola 🎭",
  "May this year write your most beautiful story 🖊️",
  "Wishing you ice cream on sad days and champagne on good ones 🍦",
  "May you always know how deeply loved you are 💓",
  "Here's to becoming who you've always dreamed of being ✨",
  "May every goodbye lead to a more beautiful hello 👋",
  "Wishing you mornings full of inspiration and evenings full of peace 🌄",
  "May your heart always find its way to love 💕",
  "You are the universe's greatest gift to those around you 🌌",
  "May success come knocking at your door this year 🏆",
  "Wishing you a life as vibrant as your personality 🎆",
  "May every step you take be guided by grace ✨",
  "Here's to all the beautiful connections you'll make 🤍",
  "May you always have something to look forward to 🎊",
  "Wishing you a year of answered prayers 🙏",
  "May your spirit remain forever young and free 🕊️",
  "You have a beautiful soul that deserves beautiful things 🌸",
  "May every challenge shape you into your best self 💎",
  "Wishing you the gift of presence in every moment 🎁",
  "May your love story be the kind that inspires others 💑",
  "Here's to dreaming big and living bigger 🚀",
  "May this year bring you everything you've been patient for ⏳",
  "Wishing you a symphony of joy and harmony 🎶",
  "May every tear be replaced with twice the laughter 😂",
  "You deserve mountains of love, oceans of happiness 🌊",
  "May your passion never fade and your fire never die 🔥",
  "Here's to the best version of you, emerging this year ⭐",
  "May you find magic in the mundane ✨",
  "Wishing you a soul-nourishing, heart-warming year 🧡",
  "May you always choose yourself and your happiness first 💫",
  "You are irreplaceable — never forget that, Rola 💖",
  "May this birthday be the beginning of your most amazing era 👑",
  "Wishing you a year of pure, unbothered joy ☀️",
  "May every milestone fill you with pride and gratitude 🏅",
  "Here's to the friendships that feel like family 👯",
  "May your heart be as full as your cup on the best mornings ☕",
  "Wishing you the courage to love fiercely and without fear ❤️",
  "May your birthday wishes ripple out into the whole year 🌊",
  "You are magic, Rola — never let anyone dim your light ✨✨✨",
];

export const getRandomWish = (): string => {
  return wishes[Math.floor(Math.random() * wishes.length)];
};
